server:
  port: 8701
spring:
  application:
    name: colin-feign-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/
feign:
  client:
    config:
      default:
        loggerLevel: FULL