server:
  port: 8201
spring:
  application:
    name: colin-user-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #eureka:
  #client:
    #register-with-eureka: true
    #fetch-registry: true
    #service-url:
      #defaultZone: http://localhost:8001/eureka